kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauth-server
  namespace: budget
spec:
  # A deployment's specification really only
  # has a few useful options

  # 1. How many copies of each pod do we want?
  replicas: 2

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: oauth-server

  # This template field is a regular pod configuration
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: oauth-server
    spec:
      containers:
        - name: oauth-server
          image: ghcr.io/mslauson/oauth-server/oauth-server:latest
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
      env:
       - name: MONGO_USER
         valueFrom:
           secretKeyRef:
             name: mongo-creds
             key: username
       - name: MONGO_PWORD
         valueFrom:
           secretKeyRef:
             name: mongo-creds
             key: password
       - name: KEY
         valueFrom:
           secretKeyRef:
             name: encryption-creds
             key: key
       - name: IV
         valueFrom:
           secretKeyRef:
             name: encryption-creds
             key: iv
       - name: MONGO_HOST
         valueFrom:
           configMapKeyRef:
             name: mongo-config
             key: host
