name: Build and Publish to Github Packages.  Deploy to Matt's

on:
  push:
    branches:
      - dev
      - main
# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_ORG: mslauson
  GITHUB_USER: ${{ github.actor }}
  GITHUB_PWORD: ${{ secrets.GITHUB_TOKEN }}
  PERSONAL_TOKEN: ${{secrets.PERSONAL_TOKEN}}
  KUBE_CONFIG: ${{secrets.KUBE_CONFIG}}
  GITHUB_PACKAGES_LOGIN: https://ghcr.io
  IMAGE: oauth-server
  REGISTRY_HOSTNAME: ghcr.io
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deployz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup gcloud CLI
      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: ECHO SHA
        run: |
          echo $GITHUB_SHA
      - name: Configure Docker
        run: |
          docker login $GITHUB_PACKAGES_LOGIN -u $GITHUB_USER -p $GITHUB_PWORD
      #          docker buildx create --use
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      # Build the Docker image
      - name: Build and Push
        run: |
          docker buildx build -t "$REGISTRY_HOSTNAME"/"$GITHUB_ORG"/"$IMAGE"/"$IMAGE":dev-"$GITHUB_SHA" \
            --build-arg token=$PERSONAL_TOKEN --push .
      - name: Set Up Kubectl
        run: |
          mkdir ~/.kube
          echo $KUBE_CONFIG | base64 -d  > ~/.kube/config
          echo "test"
          cat ~/.kube/config
      # Set up kustomize
      - name: Set up Kustomize
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          ./kustomize edit set image $REGISTRY_HOSTNAME/$GITHUB_ORG/$IMAGE/$IMAGE:dev-${GITHUB_SHA}
          ./kustomize build . | kubectl --insecure-skip-tls-verify apply -f -